import { getMeta, formatDateTime } from "./reportMeta.js";

/** Render an analysis result as plain text for Copy / Email. */
export function buildReportText(result) {
  const meta = getMeta(result);
  const lines = [
    "CYBERLENS — THREAT ANALYSIS REPORT",
    "========================================",
    `Report ID : ${meta.reportId}`,
    `Generated : ${formatDateTime(meta.scannedAt)}`,
    "Classification: CONFIDENTIAL",
    "",
    `VERDICT   : ${result.verdict}   (risk score ${result.score}/100)`,
    `Summary   : ${result.summary}`,
  ];

  if (meta.input) {
    lines.push("", "Analyzed content:", `  ${meta.input.slice(0, 600).replace(/\n/g, "\n  ")}`);
  }

  lines.push("", "DETAILED ANALYSIS", "-----------------", result.explanation || "");

  if (result.red_flags?.length) {
    lines.push("", "RED FLAGS", "---------");
    result.red_flags.forEach((f) =>
      lines.push(`  [${f.severity}] ${f.flag} — ${f.detail}`)
    );
  }

  if (result.signals?.length) {
    lines.push("", "THREAT SIGNALS", "--------------");
    result.signals.forEach((s) => lines.push(`  ${s.status} — ${s.name}: ${s.detail}`));
  }

  const vt = result.virustotal;
  if (vt?.checked) {
    lines.push(
      "",
      "VIRUSTOTAL",
      "----------",
      `  ${vt.malicious + vt.suspicious}/${vt.total_engines || "?"} engines flagged it.`
    );
    if (vt.flagged_by?.length) {
      lines.push(`  Flagged by: ${vt.flagged_by.join(", ")}`);
    }
  }

  if (result.recommendation?.length) {
    lines.push("", "RECOMMENDED ACTIONS", "-------------------");
    result.recommendation.forEach((r, i) => lines.push(`  ${i + 1}. ${r}`));
  }

  lines.push(
    "",
    "----------------------------------------",
    "Generated by CyberLens · Powered by Google Gemini + VirusTotal"
  );
  return lines.join("\n");
}
